name: meu_preco
description: "Aplicação completa para precificação de produtos e receitas. Calcule custos, margens de lucro e preços de venda de forma automática e detalhada. Ideal para empreendedores, cozinheiros e pequenos negócios."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Persistência local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Gerenciamento de estado
  provider: ^6.1.2
  
  # Formatação
  intl: ^0.19.0
  
  # Navegação
  go_router: ^14.2.0
  
  # Widgets adicionais
  flutter_slidable: ^3.0.1
  
  # Manipulação de imagens
  path_provider: ^2.1.2
  http: ^1.2.1
  path: ^1.9.1
  # Adicionando novamente o image_picker com versão específica
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  hive_generator: ^2.0.1

  # Gerador de ícones
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

# Configuração dos ícones do aplicativo
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icone.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icone.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  